on:
    push:
        branches:
            - release

jobs:
    test:
        name: test-facial-recognition
        run-on: [self-hosted,linux,ARM64]
        steps:
            name: Capture Face
            run: python3 